project:
  type: book
  output-dir: docs
  preview:
      port: 4200
      browser: false

book:
  title: "MBA Data Science - USP/ESALQ"
  lang: pt
  author: "Luiz Fernando"
  date: "10/12/2022"
  search: true
  chapters:
    - index.qmd
    - part: Módulo 0 - Nivelamento
      chapters:       
        - mod0_01_intro_estatistica.qmd
        - mod0_02_intro_r.qmd        
    - part: Módulo 1 - Unsupervised Machine Learning
      chapters:       
        - mod1_01_00_clustering.qmd
        - mod1_01_01_analise_de_cluster_vestibular.qmd
        - mod1_01_02_analise_de_cluster_paises.qmd
        - mod1_01_03_analise_de_clusters_binarias.qmd
        - mod1_01_04_analise_de_cluster_varejistas.qmd
        - mod1_01_05_analise_de_cluster_cartao.qmd

    # - intro.qmd
    # - summary.qmd
    # - references.qmd



bibliography: references.bib

format:
  html:
    theme: cosmo
    code-copy: true
    code-overflow: wrap
  #pdf:
  #  documentclass: scrreprt


execute:
  freeze: auto
  cache: true
